import { Podcast } from "../models/podcast";
import { Track } from "../models/track";

const coverImageUrl =
  "https://qirsetkyxalxkpdeotnx.supabase.co/storage/v1/object/public/cms/media/a34ab3a2-e7ac-494b-bdaf-220270b50eee.jpg";

const audioUrl =
  "https://qirsetkyxalxkpdeotnx.supabase.co/storage/v1/object/public/cms/media/1718de57-fd1f-40dc-9726-21a9d28fadb4.mp3";

export const tracks: Track[] = [
  {
    id: "1",
    title: "Midnight Drive",
    artist: "Neon Waves",
    album: "City Lights",
    coverImageUrl,
    audioUrl,
    duration: 307,
    createdBy: "admin",
    createdAt: "2025-01-10T08:30:00Z",
    updatedAt: "2025-01-10T08:30:00Z",
  },
  {
    id: "2",
    title: "Golden Hour",
    artist: "Luna Sky",
    album: "Sunset Stories",
    coverImageUrl,
    audioUrl,
    duration: 189,
    createdBy: "admin",
    createdAt: "2025-01-11T09:15:00Z",
    updatedAt: "2025-01-11T09:15:00Z",
  },
  {
    id: "3",
    title: "Echoes of You",
    artist: "Riverlane",
    album: "Reflections",
    coverImageUrl,
    audioUrl,
    duration: 242,
    createdBy: "editor",
    createdAt: "2025-01-12T10:00:00Z",
    updatedAt: "2025-01-12T10:00:00Z",
  },
  {
    id: "4",
    title: "Electric Bloom",
    artist: "Pulse Theory",
    album: "After Dark",
    coverImageUrl,
    audioUrl,
    duration: 203,
    createdBy: "editor",
    createdAt: "2025-01-13T11:45:00Z",
    updatedAt: "2025-01-13T11:45:00Z",
  },
  {
    id: "5",
    title: "Slow Motion",
    artist: "Aurora Vale",
    album: "Still Frames",
    coverImageUrl,
    audioUrl,
    duration: 256,
    createdBy: "admin",
    createdAt: "2025-01-14T14:20:00Z",
    updatedAt: "2025-01-14T14:20:00Z",
  },
  {
    id: "6",
    title: "Last Signal",
    artist: "Static Hearts",
    album: "Frequencies",
    coverImageUrl,
    audioUrl,
    duration: 221,
    createdBy: "admin",
    createdAt: "2025-01-15T16:00:00Z",
    updatedAt: "2025-01-15T16:00:00Z",
  },
];

const podcastCoverImageUrl = coverImageUrl;

const podcastAudioUrl = audioUrl;

export const podcasts: Podcast[] = [
  {
    id: "1",
    title: "Tech Talks Daily",
    author: "Alex Morgan",
    description:
      "Daily conversations about technology, startups, and innovation.",
    coverImageUrl: podcastCoverImageUrl,
    audioUrl: podcastAudioUrl,
    episodeTitle: "The Future of AI",
    episodeNumber: 101,
    duration: 307,
    createdBy: "admin",
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "2",
    title: "Mindful Minutes",
    author: "Sarah Lee",
    description: "Short episodes focused on mindfulness and mental well-being.",
    coverImageUrl: podcastCoverImageUrl,
    audioUrl: podcastAudioUrl,
    episodeTitle: "Finding Calm in Chaos",
    episodeNumber: 45,
    duration: 1500,
    createdBy: "admin",
    createdAt: "2025-01-11T09:00:00Z",
    updatedAt: "2025-01-11T09:00:00Z",
  },
  {
    id: "3",
    title: "Startup Stories",
    author: "Jason Reed",
    description: "Real stories from founders building companies from scratch.",
    coverImageUrl: podcastCoverImageUrl,
    audioUrl: podcastAudioUrl,
    episodeTitle: "From Idea to IPO",
    episodeNumber: 12,
    duration: 2100,
    createdBy: "editor",
    createdAt: "2025-01-12T10:30:00Z",
    updatedAt: "2025-01-12T10:30:00Z",
  },
  {
    id: "4",
    title: "Creative Corner",
    author: "Emily Stone",
    description: "Exploring creativity, art, and the creative process.",
    coverImageUrl: podcastCoverImageUrl,
    audioUrl: podcastAudioUrl,
    episodeTitle: "Overcoming Creative Blocks",
    episodeNumber: 78,
    duration: 1650,
    createdBy: "editor",
    createdAt: "2025-01-13T11:45:00Z",
    updatedAt: "2025-01-13T11:45:00Z",
  },
  {
    id: "5",
    title: "Health Simplified",
    author: "Dr. Nina Patel",
    description: "Breaking down health and wellness topics in simple terms.",
    coverImageUrl: podcastCoverImageUrl,
    audioUrl: podcastAudioUrl,
    episodeTitle: "Sleep Myths Explained",
    episodeNumber: 34,
    duration: 1950,
    createdBy: "admin",
    createdAt: "2025-01-14T14:15:00Z",
    updatedAt: "2025-01-14T14:15:00Z",
  },
  {
    id: "6",
    title: "Money Matters",
    author: "Chris Walker",
    description: "Personal finance tips for modern life.",
    coverImageUrl: podcastCoverImageUrl,
    audioUrl: podcastAudioUrl,
    episodeTitle: "Building Wealth in Your 20s",
    episodeNumber: 59,
    duration: 2250,
    createdBy: "admin",
    createdAt: "2025-01-15T16:00:00Z",
    updatedAt: "2025-01-15T16:00:00Z",
  },
];
